server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:8081/ctbtdemo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#输出查询数据库的sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
